Created new gentx including security contact
ingenuity-build/mainnet pull request #128
Opened 2022-12-11 22:02 UTC by valNodeOne

2022-12-14 06:46 UTC, joe-bowman requested changes
you removed the memo, which causes collect-gentxs to fail. Please update asap.

2022-12-14 16:30 UTC, valNodeOne commented
Updated memo

2022-12-15 03:23 UTC, joe-bowman approved these changes

2022-12-15 03:31 UTC, joe-bowman commented
merged / resolved conflicts

2022-12-15 03:33 UTC, closed without merging